---
zenhubServer: # FILL THIS IN - ZenHub server name, eg api.zenhub.io
zenhubApiKey: # FILL THIS IN - Generate a token in the API Tokens section of your ZenHub Dashboard (eg https://app.zenhub.com/dashboard/tokens)
githubServer: # FILL THIS IN - GitHub server, eg github.com
githubUsername: # FILL THIS IN - GitHub server username
githubPassword: # FILL THIS IN - GitHub server password (or personal access token)

# These three lists are marked as Optional, but at least one must be specified.

#(Optional) Specify a list of GitHub organizations to mirror, eg:
#orgList:
#- eclipse

#(Optional) Specify a list of GitHub uers to mirror, eg:
#userRepoList:
#- jgwest

#(Optional) Rather than specifying an org, or user, as above, one may just specify individual repos, eg:
#individualRepoList:
#- jgwest/zenhub-api-mirror

presharedKey: # FILL THIS IN - This is an arbitrary personal access token that is shared between the ZHAM server and ZHAM client.
dbPath: # FILL THIS IN - Path to a directory to store the database. If this is a relative path, it will be relative to the Open Liberty server/ directory.
